"""Email digest — sends HTML summary of brand mentions via SMTP."""

import logging
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import (
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, SMTP_FROM,
    SMTP_DIRECT_HOST, SMTP_DIRECT_PORT,
)

logger = logging.getLogger("brand-mention-monitor")


def _build_mention_html(mentions: list[dict]) -> str:
    """Build HTML body with a list of mentions."""
    date_str = datetime.now().strftime("%d.%m.%Y")

    rows_html = ""
    for m in mentions:
        title = m.get("title", "Без заголовка")
        url = m.get("url", "#")
        domain = m.get("domain", m.get("source_domain", ""))
        snippet = m.get("snippet", "")[:300]

        rows_html += f"""
        <tr>
          <td style="padding: 12px 0; border-bottom: 1px solid #eee;">
            <a href="{url}" style="color: #1a73e8; text-decoration: none; font-weight: 600; font-size: 15px;">{title}</a>
            <br/>
            <span style="display: inline-block; margin-top: 4px; padding: 2px 8px; background: #f0f0f0; border-radius: 4px; font-size: 12px; color: #555;">{domain}</span>
            <p style="margin: 6px 0 0 0; color: #333; font-size: 14px; line-height: 1.5;">{snippet}</p>
          </td>
        </tr>
        """

    html = f"""<!DOCTYPE html>
<html lang="ru">
<head><meta charset="UTF-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 640px; margin: 0 auto; padding: 20px; color: #222;">
  <h2 style="color: #1a1a1a; border-bottom: 2px solid #1a73e8; padding-bottom: 8px;">
    DDVB Media Mentions
  </h2>
  <p style="color: #666; font-size: 14px;">{date_str} &mdash; {len(mentions)} new mention(s)</p>
  <table style="width: 100%; border-collapse: collapse;">
    {rows_html}
  </table>
  <p style="margin-top: 24px; padding-top: 12px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
    Coverage count: {len(mentions)} &bull; Generated by Brand Mention Monitor
  </p>
</body>
</html>"""
    return html


def _build_empty_html() -> str:
    """Build HTML body for 'no new mentions' notification."""
    date_str = datetime.now().strftime("%d.%m.%Y")
    return f"""<!DOCTYPE html>
<html lang="ru">
<head><meta charset="UTF-8"></head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 640px; margin: 0 auto; padding: 20px; color: #222;">
  <h2 style="color: #1a1a1a; border-bottom: 2px solid #1a73e8; padding-bottom: 8px;">
    DDVB Media Mentions
  </h2>
  <p style="color: #666; font-size: 14px;">{date_str}</p>
  <p style="color: #333; font-size: 15px; line-height: 1.6;">
    No new third-party brand mentions were discovered this week.
    The monitor will continue scanning automatically.
  </p>
  <p style="margin-top: 24px; padding-top: 12px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
    Generated by Brand Mention Monitor
  </p>
</body>
</html>"""


def _send_via_relay(msg_bytes: str, recipients: list[str]) -> None:
    """Send via Selectel SMTP relay (external recipients)."""
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
        server.ehlo()
        server.starttls()
        server.ehlo()
        if SMTP_USER and SMTP_PASSWORD:
            server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(SMTP_FROM, recipients, msg_bytes)


def _send_direct(msg_bytes: str, recipients: list[str]) -> None:
    """Send directly to mail.ddvb.ru (Synology NAS) for @ddvb.ru recipients."""
    with smtplib.SMTP(SMTP_DIRECT_HOST, SMTP_DIRECT_PORT, timeout=30) as server:
        server.ehlo()
        try:
            server.starttls()
            server.ehlo()
        except smtplib.SMTPNotSupportedError:
            pass  # port 25 may not support STARTTLS
        server.sendmail(SMTP_FROM, recipients, msg_bytes)


def _send_email(subject: str, html_body: str, recipients: list[str]) -> bool:
    """Send an HTML email via SMTP. Routes @ddvb.ru directly, others via relay."""
    if not SMTP_HOST and not SMTP_DIRECT_HOST:
        logger.warning("No SMTP configured — skipping email send")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = SMTP_FROM
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(html_body, "html", "utf-8"))
    msg_bytes = msg.as_string()

    # Split recipients by delivery route
    direct = [r for r in recipients if r.endswith("@ddvb.ru")]
    relay = [r for r in recipients if not r.endswith("@ddvb.ru")]

    ok = True
    try:
        if direct and SMTP_DIRECT_HOST:
            _send_direct(msg_bytes, direct)
            logger.info("Email sent (direct) to %s", ", ".join(direct))
        elif direct:
            logger.warning("No SMTP_DIRECT_HOST — cannot deliver to %s", direct)
            ok = False

        if relay and SMTP_HOST:
            _send_via_relay(msg_bytes, relay)
            logger.info("Email sent (relay) to %s", ", ".join(relay))
        elif relay:
            logger.warning("No SMTP_HOST — cannot deliver to %s", relay)
            ok = False

    except Exception as e:
        logger.error("Failed to send email: %s", e)
        ok = False

    return ok


def send_digest(mentions: list[dict], recipients: list[str]) -> bool:
    """Send HTML email digest with mention list."""
    date_str = datetime.now().strftime("%d.%m.%Y")
    subject = f"DDVB Media Mentions — {date_str}"
    html_body = _build_mention_html(mentions)
    return _send_email(subject, html_body, recipients)


def send_empty_notification(recipients: list[str]) -> bool:
    """Send 'no new mentions this week' notification."""
    date_str = datetime.now().strftime("%d.%m.%Y")
    subject = f"DDVB Media Mentions — {date_str}"
    html_body = _build_empty_html()
    return _send_email(subject, html_body, recipients)
